# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

# sample
# stages:          # List of stages for jobs, and their order of execution
#   - build
#   - test
#   - deploy

# build-job:       # This job runs in the build stage, which runs first.
#   stage: build
#   script:
#     - echo "Compiling the code...x"
#     - echo "Compile complete."

# unit-test-job:   # This job runs in the test stage.
#   stage: test    # It only starts when the job in the build stage completes successfully.
#   script:
#     - echo "Running unit tests... This will take about 60 seconds."
#     - sleep 60
#     - echo "Code coverage is 90%"

# lint-test-job:   # This job also runs in the test stage.
#   stage: test    # It can run at the same time as unit-test-job (in parallel).
#   script:
#     - echo "Linting code... This will take about 10 seconds."
#     - sleep 10
#     - echo "No lint issues found."

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."

# here
# default:
#   image: docker:24.0.5
#   services:
#     - docker:24.0.5-dind
#   before_script:
#     - docker info
variables:
  DOCKER_IMAGE: "rhayeksa/dtc:latest"
  OPENSHIFT_APP: "dtc:latest"
stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy
build-image-and-register-to-dockerhub-job:
  tags:
    - hunter-tags
  image: docker:24.0.5
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  services:
    - docker:24.0.5-dind
  before_script:
    # - docker info
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

deploy-to-openshift-job:
  image: appuio/oc:v4.13
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'
  before_script:
    - oc login --token=$OC_TOKEN --server=$OC_SERVER
  script:
    - oc import-image $OPENSHIFT_APP --from=$DOCKER_IMAGE --confirm
    - oc autoscale dc/dtc --min 3 --max 10 --cpu-percent=80
    - oc scale --replicas=3 dc/dtc



