version: "3.1"
services:
  app:
    container_name: "django_template_component"
    build: .
    ports:
      - "8080:8000"
    # command: ["python", "./manage.py", "runserver", "0.0.0.0:8000"]
    command: "python ./manage.py runserver 0.0.0.0:8000"
